var cocktails = {
    "Mojito": {
        "Avg": "76.40625",
        "Base": "Ron Blanco",
        "CocktailId": "1",
        "Frecuency": "57",
        "IsCuban": "1",
        "Max": "125",
        "Min": "37.5",
        "Name": "Mojito",
        "NetPrice": "21.4378205128205",
        "Recipe": "https://www.ecured.cu/Mojito",
        "Selected": "1",
        "TotalPrice": "153.25"
    },
    "Sangria": {
        "Avg": "87.8125",
        "Base": "Vino",
        "CocktailId": "2",
        "Frecuency": "48",
        "IsCuban": "0",
        "Max": "125",
        "Min": "50",
        "Name": "Sangría",
        "NetPrice": "334.47483974359",
        "Recipe": "https://www.ecured.cu/Sangr%C3%ADa",
        "Selected": "1",
        "TotalPrice": "833.75"
    },
    "Cubalibre": {
        "Avg": "73.287037037037",
        "Base": "Ron Blanco",
        "CocktailId": "3",
        "Frecuency": "54",
        "IsCuban": "1",
        "Max": "125",
        "Min": "37.5",
        "Name": "Cubalibre",
        "NetPrice": "11.0714285714286",
        "Recipe": "https://www.ecured.cu/Cubalibre",
        "Selected": "1",
        "TotalPrice": "110.75"
    },
    "Daiquiri": {
        "Avg": "76.1320754716981",
        "Base": "Ron Blanco",
        "CocktailId": "4",
        "Frecuency": "53",
        "IsCuban": "1",
        "Max": "125",
        "Min": "37.5",
        "Name": "Daiquirí",
        "NetPrice": "10.2276098901099",
        "Recipe": "https://www.ecured.cu/Daiquir%C3%AD",
        "Selected": "1",
        "TotalPrice": "231.25"
    },
    "Pina Colada": {
        "Avg": "85.1415094339623",
        "Base": "Ron Blanco",
        "CocktailId": "6",
        "Frecuency": "53",
        "IsCuban": "0",
        "Max": "125",
        "Min": "37.5",
        "Name": "Piña Colada",
        "NetPrice": "36.605",
        "Recipe": "https://www.ecured.cu/Pi%C3%B1a_colada",
        "Selected": "1",
        "TotalPrice": "266.25"
    },
    "Ron Collins": {
        "Avg": "71.8154761904762",
        "Base": "Ron Blanco",
        "CocktailId": "8",
        "Frecuency": "42",
        "IsCuban": "0",
        "Max": "112.5",
        "Min": "37.5",
        "Name": "Ron Collins",
        "NetPrice": "13.2182692307692",
        "Recipe": "https://www.ecured.cu/Ron_Collins",
        "Selected": "1",
        "TotalPrice": "165.75"
    },
    "Tom Collins": {
        "Avg": "90.8035714285714",
        "Base": "Ginebra",
        "CocktailId": "9",
        "Frecuency": "14",
        "IsCuban": "0",
        "Max": "112.5",
        "Min": "62.5",
        "Name": "Tom Collins",
        "NetPrice": "19.9365384615385",
        "Recipe": "https://www.ecured.cu/C%C3%B3ctel_Tom_Collins",
        "Selected": "1",
        "TotalPrice": "229.5"
    },
    "Phil Collins": {
        "Avg": "81.25",
        "Base": "",
        "CocktailId": "10",
        "Frecuency": "2",
        "IsCuban": "0",
        "Max": "87.5",
        "Min": "75",
        "Name": "Phil Collins",
        "NetPrice": "",
        "Recipe": "",
        "Selected": "0",
        "TotalPrice": ""
    },
    "Screwdriver": {
        "Avg": "84.3181818181818",
        "Base": "Vodka",
        "CocktailId": "11",
        "Frecuency": "44",
        "IsCuban": "0",
        "Max": "150",
        "Min": "37.5",
        "Name": "Screwdriver",
        "NetPrice": "14.58",
        "Recipe": "https://www.ecured.cu/C%C3%B3ctel_Destornillador",
        "Selected": "1",
        "TotalPrice": "130"
    },
    "Caipirinha": {
        "Avg": "79.4722222222222",
        "Base": "Aguardiente",
        "CocktailId": "12",
        "Frecuency": "45",
        "IsCuban": "0",
        "Max": "150",
        "Min": "37.5",
        "Name": "Caipirinha",
        "NetPrice": "15.7980769230769",
        "Recipe": "https://www.ecured.cu/Caipirinha",
        "Selected": "1",
        "TotalPrice": "115.75"
    },
    "Caipiroska": {
        "Avg": "85.40625",
        "Base": "Vodka",
        "CocktailId": "13",
        "Frecuency": "40",
        "IsCuban": "0",
        "Max": "150",
        "Min": "37.5",
        "Name": "Caipiroska",
        "NetPrice": "12.6730769230769",
        "Recipe": "https://www.ecured.cu/Caipiroska",
        "Selected": "1",
        "TotalPrice": "122"
    },
    "Caipirissima": {
        "Avg": "77.8676470588235",
        "Base": "Ron Blanco",
        "CocktailId": "14",
        "Frecuency": "17",
        "IsCuban": "0",
        "Max": "100",
        "Min": "62.5",
        "Name": "Caipirissima",
        "NetPrice": "15.4423076923077",
        "Recipe": "http://www.cocktails-and-drinks.com/es/recetas/caipirissima",
        "Selected": "1",
        "TotalPrice": "143.25"
    },
    "Canchanchara": {
        "Avg": "87.0192307692308",
        "Base": "Aguardiente",
        "CocktailId": "15",
        "Frecuency": "13",
        "IsCuban": "1",
        "Max": "125",
        "Min": "50",
        "Name": "Canchánchara",
        "NetPrice": "7.8375",
        "Recipe": "https://www.ecured.cu/Canch%C3%A1nchara",
        "Selected": "1",
        "TotalPrice": "103.75"
    },
    "Gintonic": {
        "Avg": "99.4414893617021",
        "Base": "Ginebra",
        "CocktailId": "16",
        "Frecuency": "47",
        "IsCuban": "0",
        "Max": "150",
        "Min": "37.5",
        "Name": "Gintonic",
        "NetPrice": "19.7539393939394",
        "Recipe": "https://www.ecured.cu/C%C3%B3ctel_Gin_Tonic",
        "Selected": "1",
        "TotalPrice": "172"
    },
    "Cubata": {
        "Avg": "83.2777777777778",
        "Base": "Ron Anhejo",
        "CocktailId": "17",
        "Frecuency": "45",
        "IsCuban": "1",
        "Max": "125",
        "Min": "37.5",
        "Name": "Cubata",
        "NetPrice": "11.8892857142857",
        "Recipe": "https://www.liquor.com/recipes/cubata/",
        "Selected": "1",
        "TotalPrice": "125.75"
    },
    "Cubanito": {
        "Avg": "83.3445945945946",
        "Base": "Ron Blanco",
        "CocktailId": "18",
        "Frecuency": "37",
        "IsCuban": "1",
        "Max": "137.5",
        "Min": "37.5",
        "Name": "Cubanito",
        "NetPrice": "36.402990797546",
        "Recipe": "https://www.ecured.cu/C%C3%B3ctel_Cubanito",
        "Selected": "1",
        "TotalPrice": "310"
    },
    "Chelada": {
        "Avg": "70.5357142857143",
        "Base": "Cerveza Clara",
        "CocktailId": "19",
        "Frecuency": "7",
        "IsCuban": "0",
        "Max": "87.5",
        "Min": "57.5",
        "Name": "Chelada",
        "NetPrice": "27.084",
        "Recipe": "https://www.ecured.cu/Michelada#La_Chelada",
        "Selected": "1",
        "TotalPrice": "39"
    },
    "Michelada": {
        "Avg": "74.4583333333333",
        "Base": "Cerveza Clara",
        "CocktailId": "21",
        "Frecuency": "30",
        "IsCuban": "0",
        "Max": "125",
        "Min": "12.5",
        "Name": "Michelada",
        "NetPrice": "58.3834120654397",
        "Recipe": "https://www.ecured.cu/Michelada",
        "Selected": "1",
        "TotalPrice": "561.5"
    },
    "Bloody Mary": {
        "Avg": "97.7586206896552",
        "Base": "Vodka",
        "CocktailId": "23",
        "Frecuency": "29",
        "IsCuban": "0",
        "Max": "150",
        "Min": "56.25",
        "Name": "Bloody Mary",
        "NetPrice": "28.3395981595092",
        "Recipe": "https://www.ecured.cu/Bloody_Mary",
        "Selected": "1",
        "TotalPrice": "331.5"
    },
    "Margarita": {
        "Avg": "98.6666666666667",
        "Base": "Tequila",
        "CocktailId": "24",
        "Frecuency": "30",
        "IsCuban": "0",
        "Max": "150",
        "Min": "37.5",
        "Name": "Margarita",
        "NetPrice": "44.323880952381",
        "Recipe": "https://www.ecured.cu/C%C3%B3ctel_Margarita",
        "Selected": "1",
        "TotalPrice": "1447"
    },
    "Long Island": {
        "Avg": "128.75",
        "Base": "",
        "CocktailId": "25",
        "Frecuency": "5",
        "IsCuban": "0",
        "Max": "192.5",
        "Min": "100",
        "Name": "Long Island",
        "NetPrice": "",
        "Recipe": "",
        "Selected": "0",
        "TotalPrice": ""
    },
    "Whisky Sour": {
        "Avg": "120.25",
        "Base": "",
        "CocktailId": "26",
        "Frecuency": "5",
        "IsCuban": "0",
        "Max": "150",
        "Min": "100",
        "Name": "Whisky Sour",
        "NetPrice": "",
        "Recipe": "",
        "Selected": "0",
        "TotalPrice": ""
    },
    "Manhattan": {
        "Avg": "114.134615384615",
        "Base": "Whisky",
        "CocktailId": "27",
        "Frecuency": "13",
        "IsCuban": "0",
        "Max": "162.5",
        "Min": "73.75",
        "Name": "Manhattan",
        "NetPrice": "37.4693452380952",
        "Recipe": "https://www.ecured.cu/C%C3%B3ctel_Manhattan",
        "Selected": "1",
        "TotalPrice": "1020"
    },
    "Rontonic": {
        "Avg": "50",
        "Base": "",
        "CocktailId": "28",
        "Frecuency": "1",
        "IsCuban": "0",
        "Max": "50",
        "Min": "50",
        "Name": "Rontonic",
        "NetPrice": "",
        "Recipe": "",
        "Selected": "0",
        "TotalPrice": ""
    },
    "Vodkatonic": {
        "Avg": "94.7282608695652",
        "Base": "Vodka",
        "CocktailId": "29",
        "Frecuency": "23",
        "IsCuban": "0",
        "Max": "150",
        "Min": "37.5",
        "Name": "Vodkatonic",
        "NetPrice": "9.92045454545455",
        "Recipe": "https://www.absolutdrinks.com/es/drinks/vodka-tonic/",
        "Selected": "1",
        "TotalPrice": "87"
    },
    "Negroni": {
        "Avg": "130.9375",
        "Base": "Ginebra",
        "CocktailId": "30",
        "Frecuency": "12",
        "IsCuban": "0",
        "Max": "200",
        "Min": "73.75",
        "Name": "Negroni",
        "NetPrice": "26.4583333333333",
        "Recipe": "https://www.ecured.cu/C%C3%B3ctel_Negroni",
        "Selected": "1",
        "TotalPrice": "1162.5"
    },
    "Old Fashioned": {
        "Avg": "110.833333333333",
        "Base": "Whisky",
        "CocktailId": "31",
        "Frecuency": "9",
        "IsCuban": "0",
        "Max": "162.5",
        "Min": "87.5",
        "Name": "Old Fashioned",
        "NetPrice": "34.2760531135531",
        "Recipe": "https://www.ecured.cu/C%C3%B3ctel_Old_Fashioned",
        "Selected": "1",
        "TotalPrice": "755.75"
    },
    "Orgasm": {
        "Avg": "146.875",
        "Base": "",
        "CocktailId": "32",
        "Frecuency": "6",
        "IsCuban": "0",
        "Max": "200",
        "Min": "100",
        "Name": "Orgasm",
        "NetPrice": "",
        "Recipe": "",
        "Selected": "0",
        "TotalPrice": ""
    },
    "Cosmopolitan": {
        "Avg": "88.5416666666667",
        "Base": "",
        "CocktailId": "33",
        "Frecuency": "6",
        "IsCuban": "0",
        "Max": "112.5",
        "Min": "58.75",
        "Name": "Cosmopolitan",
        "NetPrice": "",
        "Recipe": "",
        "Selected": "0",
        "TotalPrice": ""
    },
    "President": {
        "Avg": "85.78125",
        "Base": "Ron Blanco",
        "CocktailId": "34",
        "Frecuency": "8",
        "IsCuban": "1",
        "Max": "112.5",
        "Min": "62.5",
        "Name": "President",
        "NetPrice": "9.04107142857143",
        "Recipe": "https://www.ecured.cu/C%C3%B3ctel_Presidente",
        "Selected": "1",
        "TotalPrice": "495"
    },
    "Mary Pickford": {
        "Avg": "83.125",
        "Base": "Ron Blanco",
        "CocktailId": "35",
        "Frecuency": "16",
        "IsCuban": "1",
        "Max": "150",
        "Min": "62.5",
        "Name": "Mary Pickford",
        "NetPrice": "8.36964285714286",
        "Recipe": "https://www.ecured.cu/C%C3%B3ctel_Mary_Pickford",
        "Selected": "1",
        "TotalPrice": "321.25"
    },
    "Tequila Sunrise": {
        "Avg": "102.236842105263",
        "Base": "Tequila",
        "CocktailId": "36",
        "Frecuency": "19",
        "IsCuban": "0",
        "Max": "150",
        "Min": "73.75",
        "Name": "Tequila Sunrise",
        "NetPrice": "28.1207142857143",
        "Recipe": "https://www.ecured.cu/Tequila_Sunrise",
        "Selected": "1",
        "TotalPrice": "337.5"
    },
    "Limonada Clarete": {
        "Avg": "75.7142857142857",
        "Base": "",
        "CocktailId": "38",
        "Frecuency": "7",
        "IsCuban": "0",
        "Max": "87.5",
        "Min": "55.0",
        "Name": "Limonada Clarete",
        "NetPrice": "",
        "Recipe": "",
        "Selected": "0",
        "TotalPrice": ""
    },
    "Tintoverano": {
        "Avg": "79.1666666666667",
        "Base": "",
        "CocktailId": "39",
        "Frecuency": "6",
        "IsCuban": "0",
        "Max": "100",
        "Min": "50",
        "Name": "Tintoverano",
        "NetPrice": "",
        "Recipe": "",
        "Selected": "0",
        "TotalPrice": ""
    },
    "Martini": {
        "Avg": "101.907894736842",
        "Base": "Ginebra",
        "CocktailId": "40",
        "Frecuency": "19",
        "IsCuban": "0",
        "Max": "150",
        "Min": "45",
        "Name": "Martini",
        "NetPrice": "71.77",
        "Recipe": "https://www.ecured.cu/Martini_Dry",
        "Selected": "1",
        "TotalPrice": "529.5"
    },
    "Dry Martini and Blue": {
        "Avg": "93.75",
        "Base": "",
        "CocktailId": "41",
        "Frecuency": "5",
        "IsCuban": "0",
        "Max": "112.5",
        "Min": "73.75",
        "Name": "Dry Martini and Blue",
        "NetPrice": "",
        "Recipe": "",
        "Selected": "0",
        "TotalPrice": ""
    },
    "Sex On The Beach": {
        "Avg": "97.3611111111111",
        "Base": "Vodka",
        "CocktailId": "42",
        "Frecuency": "9",
        "IsCuban": "0",
        "Max": "123.75",
        "Min": "73.75",
        "Name": "Sex On The Beach",
        "NetPrice": "21.6464285714286",
        "Recipe": "https://www.ecured.cu/C%C3%B3ctel_Sex_on_the_beach",
        "Selected": "1",
        "TotalPrice": "483.75"
    },
    "White Russian": {
        "Avg": "111.25",
        "Base": "",
        "CocktailId": "43",
        "Frecuency": "6",
        "IsCuban": "0",
        "Max": "138.75",
        "Min": "81.25",
        "Name": "White Russian",
        "NetPrice": "",
        "Recipe": "",
        "Selected": "0",
        "TotalPrice": ""
    },
    "Black Russian": {
        "Avg": "113",
        "Base": "",
        "CocktailId": "44",
        "Frecuency": "5",
        "IsCuban": "0",
        "Max": "138.75",
        "Min": "81.25",
        "Name": "Black Russian",
        "NetPrice": "",
        "Recipe": "",
        "Selected": "0",
        "TotalPrice": ""
    },
    "Blue Lagoon": {
        "Avg": "85.9375",
        "Base": "",
        "CocktailId": "45",
        "Frecuency": "4",
        "IsCuban": "0",
        "Max": "100",
        "Min": "68.75",
        "Name": "Blue Lagoon",
        "NetPrice": "",
        "Recipe": "",
        "Selected": "0",
        "TotalPrice": ""
    },
    "Havana Special": {
        "Avg": "76.5625",
        "Base": "Ron Blanco",
        "CocktailId": "46",
        "Frecuency": "24",
        "IsCuban": "1",
        "Max": "125",
        "Min": "37.5",
        "Name": "Havana Special",
        "NetPrice": "7.41607142857143",
        "Recipe": "https://www.ecured.cu/Habana_Especial",
        "Selected": "1",
        "TotalPrice": "188.75"
    },
    "Mulata": {
        "Avg": "79.375",
        "Base": "",
        "CocktailId": "47",
        "Frecuency": "6",
        "IsCuban": "0",
        "Max": "96.25",
        "Min": "55.0",
        "Name": "Mulata",
        "NetPrice": "",
        "Recipe": "",
        "Selected": "0",
        "TotalPrice": ""
    },
    "Alexander": {
        "Avg": "108.611111111111",
        "Base": "Brandy",
        "CocktailId": "48",
        "Frecuency": "9",
        "IsCuban": "0",
        "Max": "150",
        "Min": "87.5",
        "Name": "Alexander",
        "NetPrice": "22.3622023809524",
        "Recipe": "https://www.ecured.cu/C%C3%B3ctel_Alexander",
        "Selected": "1",
        "TotalPrice": "373.75"
    },
    "American": {
        "Avg": "131.25",
        "Base": "",
        "CocktailId": "49",
        "Frecuency": "4",
        "IsCuban": "0",
        "Max": "173.75",
        "Min": "87.5",
        "Name": "American",
        "NetPrice": "",
        "Recipe": "",
        "Selected": "0",
        "TotalPrice": ""
    },
    "B52": {
        "Avg": "102.5",
        "Base": "",
        "CocktailId": "50",
        "Frecuency": "5",
        "IsCuban": "0",
        "Max": "112.5",
        "Min": "100",
        "Name": "B52",
        "NetPrice": "",
        "Recipe": "",
        "Selected": "0",
        "TotalPrice": ""
    },
    "Mimosa": {
        "Avg": "100",
        "Base": "Champagne",
        "CocktailId": "51",
        "Frecuency": "4",
        "IsCuban": "0",
        "Max": "150",
        "Min": "62.5",
        "Name": "Mimosa",
        "NetPrice": "",
        "Recipe": "",
        "Selected": "0",
        "TotalPrice": ""
    },
    "Cuba Bella": {
        "Avg": "77.0833333333333",
        "Base": "",
        "CocktailId": "53",
        "Frecuency": "3",
        "IsCuban": "1",
        "Max": "81.25",
        "Min": "75",
        "Name": "Cuba Bella",
        "NetPrice": "",
        "Recipe": "",
        "Selected": "0",
        "TotalPrice": ""
    },
    "Mai Tai": {
        "Avg": "102.083333333333",
        "Base": "",
        "CocktailId": "54",
        "Frecuency": "3",
        "IsCuban": "0",
        "Max": "156.25",
        "Min": "75",
        "Name": "Mai Tai",
        "NetPrice": "",
        "Recipe": "",
        "Selected": "0",
        "TotalPrice": ""
    },
    "Sidecar": {
        "Avg": "81.25",
        "Base": "",
        "CocktailId": "55",
        "Frecuency": "2",
        "IsCuban": "0",
        "Max": "87.5",
        "Min": "75",
        "Name": "Sidecar",
        "NetPrice": "",
        "Recipe": "",
        "Selected": "0",
        "TotalPrice": ""
    },
    "Cnc": {
        "Avg": "112.5",
        "Base": "",
        "CocktailId": "56",
        "Frecuency": "1",
        "IsCuban": "0",
        "Max": "112.5",
        "Min": "112.5",
        "Name": "Cnc",
        "NetPrice": "",
        "Recipe": "",
        "Selected": "0",
        "TotalPrice": ""
    },
    "Goodfather": {
        "Avg": "116.666666666667",
        "Base": "",
        "CocktailId": "57",
        "Frecuency": "3",
        "IsCuban": "0",
        "Max": "125",
        "Min": "100",
        "Name": "Goodfather",
        "NetPrice": "",
        "Recipe": "",
        "Selected": "0",
        "TotalPrice": ""
    },
    "Summer Red Wine": {
        "Avg": "89.5833333333333",
        "Base": "",
        "CocktailId": "58",
        "Frecuency": "6",
        "IsCuban": "0",
        "Max": "112.5",
        "Min": "75",
        "Name": "Summer Red Wine",
        "NetPrice": "",
        "Recipe": "",
        "Selected": "0",
        "TotalPrice": ""
    },
    "Aviation": {
        "Avg": "75",
        "Base": "",
        "CocktailId": "59",
        "Frecuency": "1",
        "IsCuban": "0",
        "Max": "75",
        "Min": "75",
        "Name": "Aviation",
        "NetPrice": "",
        "Recipe": "",
        "Selected": "0",
        "TotalPrice": ""
    },
    "Campari Orange": {
        "Avg": "131.25",
        "Base": "",
        "CocktailId": "60",
        "Frecuency": "2",
        "IsCuban": "0",
        "Max": "162.5",
        "Min": "100",
        "Name": "Campari Orange",
        "NetPrice": "",
        "Recipe": "",
        "Selected": "0",
        "TotalPrice": ""
    }
};

var ingredients = {
    "Mojito": ["Ron blanco", "Azúcar", "Hierbabuena", "Agua Mineral Carbonatada", "Limón"],
    "Sangria": ["Vino tinto", "Zumo Naranja", "Azúcar", "Angostura", "Vermouth Rojo", "Melocotón", "Naranja", "Manzana", "Plátano"],
    "Cubalibre": ["Refresco Cola", "Ron blanco", "Limón"],
    "Daiquiri": ["Ron blanco", "Jugo de limón", "Azúcar", "Licor de Marrasquino"],
    "Pina Colada": ["Ron blanco", "Jugo de Piña", "Crema de Coco", "Piña"],
    "Ron Collins": ["Ron blanco", "Jugo de limón", "Azúcar", "Agua Mineral Carbonatada", "Limón", "Cereza"],
    "Tom Collins": ["Ginebra", "Jugo de limón", "Azúcar", "Agua Mineral Carbonatada", "Limón"],
    "Screwdriver": ["Vodka", "Zumo Naranja"],
    "Caipirinha": ["Aguardiente", "Azúcar", "Limón"],
    "Caipiroska": ["Vodka", "Azúcar", "Limón"],
    "Caipirissima": ["Ron blanco", "Azúcar", "Limón"],
    "Canchanchara": ["Jugo de limón", "Aguardiente", "Miel de abeja"],
    "Gintonic": ["Ginebra", "Agua Tónica", "Limón"],
    "Cubata": ["Refresco Cola", "Limón", "Ron oscuro"],
    "Cubanito": ["Ron blanco", "Jugo de limón", "Salsa inglesa", "Salsa Tabasco", "Jugo de Tomate"],
    "Chelada": ["Cerveza", "Limón", "Sal"],
    "Michelada": ["Cerveza", "Jugo de limón", "Salsa inglesa", "Salsa Tabasco", "Limón", "Sal", "Chile en polvo(Pimentón Picante)", "Salsa de Soja", "Pimienta Negra"],
    "Bloody Mary": ["Vodka", "Salsa inglesa", "Salsa Tabasco", "Limón", "Sal", "Jugo de Tomate", "Pimienta Negra"],
    "Margarita": ["Jugo de limón", "Sal", "Tequila", "Cointreau"],
    "Manhattan": ["Whisky Bourbon", "Angostura", "Vermouth Rojo"],
    "Vodkatonic": ["Vodka", "Agua Tónica", "Limón"],
    "Negroni": ["Ginebra", "Vermouth Rojo", "Campari"],
    "Old Fashioned": ["Azúcar", "Agua Mineral Carbonatada", "Limón", "Whisky Bourbon", "Angostura", "Cereza", "Naranja"],
    "President": ["Ron blanco", "Licor de Granadina", "Vermouth Rojo", "Cereza", "Naranja"],
    "Mary Pickford": ["Ron blanco", "Zumo de Piña", "Licor de Marrasquino", "Licor de Granadina", "Cereza"],
    "Tequila Sunrise": ["Zumo Naranja", "Licor de Granadina", "Tequila", "Naranja"],
    "Martini": ["Ginebra", "Limón", "Vermouth Seco", "Aceitunas"],
    "Sex On The Beach": ["Vodka", "Zumo Naranja", "Licor de Granadina", "Licor de Melocotón"],
    "Havana Special": ["Ron blanco", "Licor de Marrasquino", "Jugo de Piña", "Piña"],
    "Alexander": ["Brandy", "Licor de Cacao", "Nata líquida (Crema de Leche)", "Nuez moscada"]
};

var products = {
    "Refresco Cola": {
        "Aport": "1",
        "Brand": "TuKola",
        "Name": "Refresco Cola",
        "Price": "12.5",
        "ProductId": "1",
        "Size": "350"
    },
    "Vino tinto": {
        "Aport": "1",
        "Brand": "Campo Alegre",
        "Name": "Vino tinto",
        "Price": "96.25",
        "ProductId": "2",
        "Size": "1000"
    },
    "Ron blanco": {
        "Aport": "1",
        "Brand": "Havana Club",
        "Name": "Ron blanco",
        "Price": "96.25",
        "ProductId": "3",
        "Size": "700"
    },
    "Vodka": {
        "Aport": "1",
        "Brand": "Regenta",
        "Name": "Vodka",
        "Price": "75",
        "ProductId": "4",
        "Size": "1000"
    },
    "Ginebra": {
        "Aport": "1",
        "Brand": "Contessa",
        "Name": "Ginebra",
        "Price": "160",
        "ProductId": "5",
        "Size": "750"
    },
    "Agua Tónica": {
        "Aport": "1",
        "Brand": "Ciego Montero",
        "Name": "Agua Tonica",
        "Price": "10",
        "ProductId": "6",
        "Size": "330"
    },
    "Cerveza": {
        "Aport": "1",
        "Brand": "Cristal",
        "Name": "Cerveza",
        "Price": "25",
        "ProductId": "7",
        "Size": "350"
    },
    "Jugo de limón": {
        "Aport": "1",
        "Brand": "Del Real",
        "Name": "Jugo de limon",
        "Price": "12.5",
        "ProductId": "8",
        "Size": "200"
    },
    "Zumo Naranja": {
        "Aport": "1",
        "Brand": "La Estancia",
        "Name": "Zumo Naranja",
        "Price": "55",
        "ProductId": "10",
        "Size": "1000"
    },
    "Salsa inglesa": {
        "Aport": "1",
        "Brand": "La Dona",
        "Name": "Salsa inglesa",
        "Price": "30",
        "ProductId": "11",
        "Size": "163"
    },
    "Aguardiente": {
        "Aport": "1",
        "Brand": "Santero",
        "Name": "Aguardiente",
        "Price": "68.75",
        "ProductId": "14",
        "Size": "500"
    },
    "Salsa Tabasco": {
        "Aport": "1",
        "Brand": "",
        "Name": "Salsa Tabasco",
        "Price": "153.75",
        "ProductId": "15",
        "Size": "60"
    },
    "Azúcar": {
        "Aport": "1",
        "Brand": "Buen dia",
        "Name": "Azucar",
        "Price": "45",
        "ProductId": "16",
        "Size": "130"
    },
    "Hierbabuena": {
        "Aport": "0",
        "Brand": "",
        "Name": "Hierbabuena",
        "Price": "",
        "ProductId": "17",
        "Size": ""
    },
    "Agua Mineral Carbonatada": {
        "Aport": "1",
        "Brand": "Ciego Montero",
        "Name": "Agua Mineral Carbonatada",
        "Price": "10",
        "ProductId": "18",
        "Size": "300"
    },
    "Limón": {
        "Aport": "1",
        "Brand": "",
        "Name": "Limon",
        "Price": "2",
        "ProductId": "20",
        "Size": "1"
    },
    "Sal": {
        "Aport": "1",
        "Brand": "",
        "Name": "Sal",
        "Price": "12",
        "ProductId": "21",
        "Size": "1000"
    },
    "Jugo de Tomate": {
        "Aport": "1",
        "Brand": "La Conchita",
        "Name": "Jugo de Tomate",
        "Price": "17.5",
        "ProductId": "22",
        "Size": "200"
    },
    "Zumo de Piña": {
        "Aport": "1",
        "Brand": "",
        "Name": "Zumo de Pina",
        "Price": "70",
        "ProductId": "23",
        "Size": "1000"
    },
    "Licor de Marrasquino": {
        "Aport": "1",
        "Brand": "Cubay",
        "Name": "Licor de Marrasquino",
        "Price": "77.5",
        "ProductId": "24",
        "Size": "700"
    },
    "Licor de Granadina": {
        "Aport": "1",
        "Brand": "Cubay",
        "Name": "Licor de Granadina",
        "Price": "77.5",
        "ProductId": "25",
        "Size": "700"
    },
    "Whisky Bourbon": {
        "Aport": "1",
        "Brand": "Buffalo Bill",
        "Name": "Whisky Bourbon",
        "Price": "382.5",
        "ProductId": "26",
        "Size": "700"
    },
    "Tequila": {
        "Aport": "1",
        "Brand": "Rio Club",
        "Name": "Tequila",
        "Price": "205",
        "ProductId": "29",
        "Size": "700"
    },
    "Angostura": {
        "Aport": "1",
        "Brand": "",
        "Name": "Angostura",
        "Price": "316.25",
        "ProductId": "30",
        "Size": "200"
    },
    "Licor de Melocotón": {
        "Aport": "1",
        "Brand": "Spar",
        "Name": "Licor de Melocoton",
        "Price": "276.25",
        "ProductId": "34",
        "Size": "700"
    },
    "Cointreau": {
        "Aport": "1",
        "Brand": "",
        "Name": "Cointreau",
        "Price": "1217.5",
        "ProductId": "35",
        "Size": "750"
    },
    "Miel de abeja": {
        "Aport": "1",
        "Brand": "Apisun",
        "Name": "Miel de abeja",
        "Price": "22.5",
        "ProductId": "36",
        "Size": "250"
    },
    "Vermouth Rojo": {
        "Aport": "1",
        "Brand": "Olave",
        "Name": "Vermouth Rojo",
        "Price": "321.25",
        "ProductId": "38",
        "Size": "750"
    },
    "Jugo de Piña": {
        "Aport": "1",
        "Brand": "",
        "Name": "Jugo de Pina",
        "Price": "15",
        "ProductId": "39",
        "Size": "1000"
    },
    "Crema de Coco": {
        "Aport": "1",
        "Brand": "",
        "Name": "Crema de Coco",
        "Price": "155",
        "ProductId": "40",
        "Size": "500"
    },
    "Piña": {
        "Aport": "0",
        "Brand": "",
        "Name": "Pina",
        "Price": "",
        "ProductId": "42",
        "Size": ""
    },
    "Cereza": {
        "Aport": "0",
        "Brand": "",
        "Name": "Cereza",
        "Price": "",
        "ProductId": "43",
        "Size": ""
    },
    "Melocotón": {
        "Aport": "0",
        "Brand": "",
        "Name": "Melocoton",
        "Price": "",
        "ProductId": "44",
        "Size": ""
    },
    "Naranja": {
        "Aport": "0",
        "Brand": "",
        "Name": "Naranja",
        "Price": "",
        "ProductId": "45",
        "Size": ""
    },
    "Manzana": {
        "Aport": "0",
        "Brand": "",
        "Name": "Manzana",
        "Price": "",
        "ProductId": "46",
        "Size": ""
    },
    "Plátano": {
        "Aport": "0",
        "Brand": "",
        "Name": "Platano",
        "Price": "",
        "ProductId": "47",
        "Size": ""
    },
    "Chile en polvo(Pimentón Picante)": {
        "Aport": "1",
        "Brand": "La Barraca",
        "Name": "Chile en polvo(Pimenton Picante)",
        "Price": "28.75",
        "ProductId": "48",
        "Size": "25"
    },
    "Salsa de Soja": {
        "Aport": "1",
        "Brand": "Kikkoman",
        "Name": "Salsa de Soja",
        "Price": "256.25",
        "ProductId": "49",
        "Size": "150"
    },
    "Pimienta Negra": {
        "Aport": "1",
        "Brand": "La Barraca",
        "Name": "Pimienta Negra",
        "Price": "41.25",
        "ProductId": "50",
        "Size": "25"
    },
    "Campari": {
        "Aport": "1",
        "Brand": "",
        "Name": "Campari",
        "Price": "681.25",
        "ProductId": "51",
        "Size": "1000"
    },
    "Vermouth Seco": {
        "Aport": "1",
        "Brand": "Cinzano",
        "Name": "Vermouth Seco",
        "Price": "355",
        "ProductId": "52",
        "Size": "750"
    },
    "Aceitunas": {
        "Aport": "1",
        "Brand": "Spar",
        "Name": "Aceitunas",
        "Price": "12.5",
        "ProductId": "53",
        "Size": "180"
    },
    "Brandy": {
        "Aport": "1",
        "Brand": "Spirit",
        "Name": "Brandy",
        "Price": "210",
        "ProductId": "54",
        "Size": "700"
    },
    "Licor de Cacao": {
        "Aport": "1",
        "Brand": "Cubay",
        "Name": "Licor de Cacao",
        "Price": "77.5",
        "ProductId": "55",
        "Size": "700"
    },
    "Nata líquida (Crema de Leche)": {
        "Aport": "1",
        "Brand": "Nestle",
        "Name": "Nata liquida (Crema de Leche)",
        "Price": "48.75",
        "ProductId": "56",
        "Size": "225"
    },
    "Nuez moscada": {
        "Aport": "1",
        "Brand": "Spar",
        "Name": "Nuez moscada",
        "Price": "37.5",
        "ProductId": "57",
        "Size": "16"
    },
    "Ron oscuro": {
        "Aport": "1",
        "Brand": "Havana Club",
        "Name": "Ron oscuro",
        "Price": "111.25",
        "ProductId": "58",
        "Size": "500"
    }
};